apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinot-component-web-deployment
  namespace: data-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinot-component-web
  template:
    metadata:
      labels:
        app: pinot-component-web
    spec:
      containers:
      - name: pinot-component-web
        image: kindservices/datamesh-component-pinot-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: pinot-registry-sidecar
        image: kindservices/datamesh-service-registry-client:latest
        imagePullPolicy: Always
        env:
          - name: HOSTPORT
            value: "http://service-registry-service.data-mesh:8080"
          - name: ID
            value: pinot-component-web
          - name: FREQUENCY_IN_SECONDS
            value: "3"
          - name: BODY
            value: '{"webComponent":{"jsUrl":"http://pinot-component-web.data-mesh/bundle.js","cssUrl":"http://pinot-component-web.data-mesh/bundle.css","componentId":"<pinot-grid card_title=\"some title\" card_desc=\"some desc\"></pinot-grid>"},"label":"Pinot Grid","tags":{"props":"card_title,card_desc"}}'
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: pinot-component-web
  namespace: data-mesh
spec:
  type: LoadBalancer
  sessionAffinity: None
  selector:
    app: pinot-component-web
  ports:
  - name : default
    port: 80
    targetPort: 80