run:
	scala-cli App.scala 
build: clean
	. ./build.sh && build
buildDocker:
	. ./build.sh && buildDocker
push: build
	. ./build.sh && push
pushOnly:
	. ./build.sh && push
clean:
	. ./build.sh && clean
installArgo:
	. ./build.sh && installArgo
uninstallArgo:
	. ./build.sh && uninstallArgo