apiVersion: apps/v1
kind: Deployment
metadata:
  name: datamesh-component-pinot-bff-deployment
  namespace: data-mesh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datamesh-component-pinot-bff
  template:
    metadata:
      labels:
        app: datamesh-component-pinot-bff
    spec:
      containers:
      - name: datamesh-component-pinot-bff
        image: kindservices/datamesh-component-pinot-bff:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: datamesh-component-pinot-bff-service
  namespace: data-mesh
spec:
  type: LoadBalancer
  sessionAffinity: None
  selector:
    app: datamesh-component-pinot-bff
  ports:
  - name : default
    port: 8080
    targetPort: 8080